const totalImpressions = [
  {
    ImpressionCount: "146330",
    customer_id: "2",
    client_currency: "£",
  },
];

const totalClicks = [
  {
    ClickCount: "5400",
    customer_id: "2",
    client_currency: "£",
  },
];

const totalCtr = [
  {
    CtrCount: "3.6899",
    customer_id: "2",
    client_currency: "£",
  },
];

const clicksMonthlyTrend = [
  {
    log_date: 1716163200,
    ClickCount: "852",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 20, 2024 12:00 AM",
  },
  {
    log_date: 1716249600,
    ClickCount: "754",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 21, 2024 12:00 AM",
  },
  {
    log_date: 1716336000,
    ClickCount: "751",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 22, 2024 12:00 AM",
  },
  {
    log_date: 1716422400,
    ClickCount: "749",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 23, 2024 12:00 AM",
  },
  {
    log_date: 1716508800,
    ClickCount: "769",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 24, 2024 12:00 AM",
  },
  {
    log_date: 1716595200,
    ClickCount: "762",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 25, 2024 12:00 AM",
  },
  {
    log_date: 1716681600,
    ClickCount: "762",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 26, 2024 12:00 AM",
  },
];

const ctrMonthlyTrend = [
  {
    log_date: 1716163200,
    CtrCount: "4.3372",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 20, 2024 12:00 AM",
  },
  {
    log_date: 1716249600,
    CtrCount: "4.0551",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 21, 2024 12:00 AM",
  },
  {
    log_date: 1716336000,
    CtrCount: "4.4692",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 22, 2024 12:00 AM",
  },
  {
    log_date: 1716422400,
    CtrCount: "3.1610",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 23, 2024 12:00 AM",
  },
  {
    log_date: 1716508800,
    CtrCount: "3.5945",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 24, 2024 12:00 AM",
  },
  {
    log_date: 1716595200,
    CtrCount: "3.3000",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 25, 2024 12:00 AM",
  },
  {
    log_date: 1716681600,
    CtrCount: "3.2995",
    customer_id: "2",
    client_currency: "£",
    timegroup: "hourly",
    formatted_log_date: "May 26, 2024 12:00 AM",
  },
];

const impressionsByState = [
  {
    region_id: "32474",
    name: "Unknown",
    ImpressionCount: "192",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32485",
    name: "Texas",
    ImpressionCount: "19231078",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32550",
    name: "Alabama",
    ImpressionCount: "27073",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32551",
    name: "Alaska",
    ImpressionCount: "2301",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32552",
    name: "Arizona",
    ImpressionCount: "12831",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32553",
    name: "Arkansas",
    ImpressionCount: "11860",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32554",
    name: "California",
    ImpressionCount: "82811",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32555",
    name: "Colorado",
    ImpressionCount: "15874",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32556",
    name: "Connecticut",
    ImpressionCount: "6469",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32557",
    name: "Delaware",
    ImpressionCount: "2450",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32558",
    name: "Florida",
    ImpressionCount: "52335",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32559",
    name: "Georgia",
    ImpressionCount: "22575",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32560",
    name: "Hawaii",
    ImpressionCount: "3381",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32561",
    name: "Idaho",
    ImpressionCount: "3290",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32562",
    name: "Illinois",
    ImpressionCount: "49550",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32563",
    name: "Indiana",
    ImpressionCount: "17239",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32564",
    name: "Iowa",
    ImpressionCount: "8743",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32565",
    name: "Kansas",
    ImpressionCount: "9581",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32566",
    name: "Kentucky",
    ImpressionCount: "14393",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32567",
    name: "Louisiana",
    ImpressionCount: "23472",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32568",
    name: "Maine",
    ImpressionCount: "4572",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32569",
    name: "Maryland",
    ImpressionCount: "11156",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32570",
    name: "Massachusetts",
    ImpressionCount: "13118",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32571",
    name: "Michigan",
    ImpressionCount: "23689",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32572",
    name: "Minnesota",
    ImpressionCount: "11870",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32573",
    name: "Mississippi",
    ImpressionCount: "11415",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32574",
    name: "Missouri",
    ImpressionCount: "18425",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32575",
    name: "Montana",
    ImpressionCount: "2956",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32576",
    name: "Nebraska",
    ImpressionCount: "4968",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32577",
    name: "Nevada",
    ImpressionCount: "5641",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32578",
    name: "New Hampshire",
    ImpressionCount: "3013",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32579",
    name: "New Jersey",
    ImpressionCount: "14398",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32580",
    name: "New Mexico",
    ImpressionCount: "5354",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32581",
    name: "New York",
    ImpressionCount: "30895",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32582",
    name: "North Carolina",
    ImpressionCount: "29956",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32583",
    name: "North Dakota",
    ImpressionCount: "1769",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32584",
    name: "Ohio",
    ImpressionCount: "27163",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32585",
    name: "Oklahoma",
    ImpressionCount: "14828",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32586",
    name: "Oregon",
    ImpressionCount: "10383",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32587",
    name: "Pennsylvania",
    ImpressionCount: "26486",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32588",
    name: "Rhode Island",
    ImpressionCount: "2405",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32589",
    name: "South Carolina",
    ImpressionCount: "13163",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32590",
    name: "South Dakota",
    ImpressionCount: "2385",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32591",
    name: "Tennessee",
    ImpressionCount: "25566",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32594",
    name: "Utah",
    ImpressionCount: "3817",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32595",
    name: "Vermont",
    ImpressionCount: "2635",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32596",
    name: "Virginia",
    ImpressionCount: "22423",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32597",
    name: "Washington",
    ImpressionCount: "12883",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32598",
    name: "Washington, District of Columbia",
    ImpressionCount: "817",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32599",
    name: "West Virginia",
    ImpressionCount: "7345",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32600",
    name: "Wisconsin",
    ImpressionCount: "14747",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "32601",
    name: "Wyoming",
    ImpressionCount: "1523",
    country: "US",
    client_currency: "£",
  },
  {
    region_id: "34841",
    name: "Zuid-Holland",
    ImpressionCount: "1",
    country: "NL",
    client_currency: "£",
  },
];

const impressionsByAgeAndGender = [
  {
    gender: "female",
    genderages_id: "76156",
    age: "35-44",
    ImpressionCount: "1660396",
    client_currency: "£",
  },
  {
    gender: "female",
    genderages_id: "76173",
    age: "18-24",
    ImpressionCount: "322888",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76174",
    age: "18-24",
    ImpressionCount: "428465",
    client_currency: "£",
  },
  {
    gender: "female",
    genderages_id: "76175",
    age: "25-34",
    ImpressionCount: "1038817",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76176",
    age: "25-34",
    ImpressionCount: "1342984",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76177",
    age: "25-34",
    ImpressionCount: "13370",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76179",
    age: "35-44",
    ImpressionCount: "1714914",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76180",
    age: "35-44",
    ImpressionCount: "32427",
    client_currency: "£",
  },
  {
    gender: "female",
    genderages_id: "76181",
    age: "45-54",
    ImpressionCount: "1804508",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76182",
    age: "45-54",
    ImpressionCount: "1574111",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76183",
    age: "45-54",
    ImpressionCount: "30426",
    client_currency: "£",
  },
  {
    gender: "female",
    genderages_id: "76184",
    age: "55-64",
    ImpressionCount: "2299152",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76185",
    age: "55-64",
    ImpressionCount: "1755253",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76186",
    age: "55-64",
    ImpressionCount: "28242",
    client_currency: "£",
  },
  {
    gender: "female",
    genderages_id: "76187",
    age: "65+",
    ImpressionCount: "3520979",
    client_currency: "£",
  },
  {
    gender: "male",
    genderages_id: "76188",
    age: "65+",
    ImpressionCount: "2364188",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76189",
    age: "65+",
    ImpressionCount: "41024",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "76254",
    age: "18-24",
    ImpressionCount: "7125",
    client_currency: "£",
  },
  {
    gender: "unknown",
    genderages_id: "83558",
    age: "Unknown",
    ImpressionCount: "0",
    client_currency: "£",
  },
];

const impressionByDevice = [
  {
    device_platform: "desktop",
    ImpressionCount: "2086852",
    client_currency: "£",
  },
  {
    device_platform: "mobile_app",
    ImpressionCount: "17871594",
    client_currency: "£",
  },
  {
    device_platform: "mobile_web",
    ImpressionCount: "20369",
    client_currency: "£",
  },
  {
    device_platform: "unknown",
    ImpressionCount: "454",
    client_currency: "£",
  },
];

const chartPalette = [
  "#0665a2",
  "#ffc930",
  "#e96455",
  "#e11272",
  "#57df7f",
  "#820970",
  "#7f2ccb",
  "#52ffee",
  "#4adf62",
  "#009630",
];
